Feature: Card Deck

Scenario: Shuffle
  When the user visits the home page
  Then they should see the "Shuffle" button 
  And they should see all cards in correct order
  When the user clicks on the "Shuffle" button
  Then they should see all cards in random order
  # Then they should see "2 Diamond"
  # And they should see "3 Diamond"
  # And they should see "4 Diamond"
  # And they should see "5 Diamond"
  # And they should see "6 Diamond"
  # And they should see "7 Diamond"
  # And they should see "8 Diamond"
  # And they should see "9 Diamond"
  # And they should see "10 Diamond"
  # And they should see "2 Heart"
  # And they should see "3 Heart"
  # And they should see "4 Heart"
  # And they should see "5 Heart"
  # And they should see "6 Heart"
  # And they should see "7 Heart"
  # And they should see "8 Heart"
  # And they should see "9 Heart"
  # And they should see "10 Heart"
  # And they should see "2 Club"
  # And they should see "3 Club"
  # And they should see "4 Club"
  # And they should see "5 Club"
  # And they should see "6 Club"
  # And they should see "7 Club"
  # And they should see "8 Club"
  # And they should see "9 Club"
  # And they should see "10 Club"
  # And they should see "2 Spade"
  # And they should see "3 Spade"
  # And they should see "4 Spade"
  # And they should see "5 Spade"
  # And they should see "6 Spade"
  # And they should see "7 Spade"
  # And they should see "8 Spade"
  # And they should see "9 Spade"
  # And they should see "10 Spade"
  # And they should see "Jack Diamond"
  # And they should see "Queen Diamond"
  # And they should see "King Diamond"
  # And they should see "Ace Diamond"
  # And they should see "Jack Heart"
  # And they should see "Queen Heart"
  # And they should see "King Heart"
  # And they should see "Ace Heart"
  # And they should see "Jack Spade"
  # And they should see "Queen Spade"
  # And they should see "King Spade"
  # And they should see "Ace Spade"
  # And they should see "Jack Club"
  # And they should see "Queen Club"
  # And they should see "King Club"
  # And they should see "Ace Club"
  # And they should see "Joker"